// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/jikan-rest-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"anime | character | club | external | genre | magazine | manga | people_search | person | producer | random | recommendation | review | schedule | season | top | user | user_about | user_club | user_friend | user_history | user_statistic | user_update | watch_episode | watch_promo"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.JikanRestSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "jikan-rest_list",
		Description: "List records from JikanRest. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "jikan-rest_load",
		Description: "Load a single record from JikanRest. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.JikanRestSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.JikanRestSDK, name string) (sdk.JikanRestEntity, error) {
	switch strings.ToLower(name) {
	case "anime":
		return client.Anime(nil), nil
	case "character":
		return client.Character(nil), nil
	case "club":
		return client.Club(nil), nil
	case "external":
		return client.External(nil), nil
	case "genre":
		return client.Genre(nil), nil
	case "magazine":
		return client.Magazine(nil), nil
	case "manga":
		return client.Manga(nil), nil
	case "people_search":
		return client.PeopleSearch(nil), nil
	case "person":
		return client.Person(nil), nil
	case "producer":
		return client.Producer(nil), nil
	case "random":
		return client.Random(nil), nil
	case "recommendation":
		return client.Recommendation(nil), nil
	case "review":
		return client.Review(nil), nil
	case "schedule":
		return client.Schedule(nil), nil
	case "season":
		return client.Season(nil), nil
	case "top":
		return client.Top(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_about":
		return client.UserAbout(nil), nil
	case "user_club":
		return client.UserClub(nil), nil
	case "user_friend":
		return client.UserFriend(nil), nil
	case "user_history":
		return client.UserHistory(nil), nil
	case "user_statistic":
		return client.UserStatistic(nil), nil
	case "user_update":
		return client.UserUpdate(nil), nil
	case "watch_episode":
		return client.WatchEpisode(nil), nil
	case "watch_promo":
		return client.WatchPromo(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
